[package]
name = "vcf_mcp_server"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
noodles = { version = "0.101.0", features = ["tabix", "vcf"] }
rmcp = { version = "0.8", features = ["server"] }
